### ISSUE TITLE
Remove actions param from Policy.decide() or change it to action_space

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#144]
Not all action_spaces can be specified as a discrete set/list, so instead of accepting the set of possible actions to `Policy.decide()` as in...

https://github.com/agentos-project/agentos/blob/632089937b9d6f34ae654feb62a233a426575bf1/agentos/core.py#L134

... `Policy.decide()` should access the action_space directly from whichever other component owns the action_space in order to find out the action_space (e.g., if using a gym Env, then the the env itself exposes the action_space; for DeepMind envs, the action_space is owned by an EnvSpec).

This is another thing that allowing components to specify arbitrary other components as dependencies would simplify (since then a policy can declare, e.g., a dependency on an EnvSpec component or an Env component as necessary to get access to the action_space).

**Comment by andyk** [comment]
FYI, this should be resolved in my work on hierarchical components (#136), working branch is currently https://github.com/andyk/agentos/tree/wip-sb3-on-master

**Comment by nickjalbert** [comment]
👍
