### ISSUE TITLE
Replace Git dependy with Dulwich dependency

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#198]
From our discussion in #195 this morning regarding a pure Python implementation of the Git functionality we need for our Component/Repo abstractions:

> dulwich is a Python implementation of git that's pip installable and importable. Tested it out on the REPL and seems like we could use this instead of relying on git to be installed locally. I think I'll hold off on this for now, though, and work on the end-to-end stuff.

**Comment by nickjalbert** [comment]
Fixed in #195
