### ISSUE TITLE
Weird MLflow error occurs when an uncaught exception gets raised during a run

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#231]
@nickjalbert reported in this https://github.com/agentos-project/agentos/pull/227#pullrequestreview-868820513 that he saw a weird MLflow error occur when an uncaught exception gets raised during a run.

Then link on that code review comment doesn't take me anywhere so I'm not sure how to reproduce what you saw. Can you describe it in more detail here so I can fix it?

**Comment by nickjalbert** [comment]
Ahh!  I just sent you an email about it.  Apparently linking within the GH comment accordion is broken (I also suspect you missed the GH comment accordion).

Comment accordion:

![Screenshot 2022-02-04 134751](https://user-images.githubusercontent.com/25208102/152493720-ef228e25-b3c5-4444-b0f4-0cc4636ceefd.png)

The bug:

![mlflow](https://user-images.githubusercontent.com/25208102/152493758-ab0a4560-adff-4362-92f3-c4a724d958f0.png)
