### ISSUE TITLE
`install_requirements.py` should work with `pip3`

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#237]
`install_requirements.py` currently assume the pip command is `pip`. On some machines (e.g., a vanilla Ubuntu instance on EC2) the pre-installed pip command is `pip3` to parallel the default `python3` command. It would be nice if our install_requirements.py checked to see if `pip3` exists and tries using that before failing.

**Comment by dimitrios-ath** [comment]
Hello, can I contribute in this one?
Thanks

**Comment by andyk** [comment]
Sure! Feel free to take a stab at it and open a PR with your contributions.

Makes sure to check out https://github.com/agentos-project/agentos#development-process for our policies about making contributions.

**Comment by dimitrios-ath** [comment]
Hi again,
I created a pull request resolving this issue. All tests passed successfully locally. This one is my first commit in a public project, so I hope my code is fine.
Thanks

**Comment by andyk** [comment]
Closed by @dimitrios-ath in #246 . Thanks @dimitrios-ath!!
