### ISSUE TITLE
Replace `Component.Identifier` uses with `ComponentIdentifier`

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#243]
I know I suggested we use an inner class for `ComponentIdentifier` in the first place, but now that we've been working with it for a while, I feel like it's confusing to have both `ComponentIdentier` and `Component.Identifier` and we should delete the inner class `Component.Identifier` (which is just an alias anyway) and replace all uses of it with `ComponentIdentifier`.

**Comment by nickjalbert** [comment]
👍
