### ISSUE TITLE
Support requirements declared via setup.py

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#275]
Currently Component Specs allow a requirements.txt to be specified via the "requirements_file" spec field. Many of [the RL frameworks](https://docs.google.com/spreadsheets/d/1r68IytgMKmZ7Se0teY0LlRRE7YLzflu4v1LuO-UK1Vs/edit#gid=265043462) we have encountered specify their requirements via a `setup.py` instead of a `requirements.txt` file. We should support both.

For example, the following projcects have a setup.py:

- https://github.com/rail-berkeley/rlkit (Ashvin & VItchyr's)
- https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail (Ilya's repo)
- https://github.com/facebookresearch/ReAgent
- https://github.com/DLR-RM/stable-baselines3
- https://github.com/takuseno/d3rlpy -- has both setup.py and requirements.txt

**Comment by nickjalbert** [comment]
This seems doable!

Does it seem reasonable to keep the same key in the spec (`requirements_file`) and then auto-detect if it's a pip file or setup.py?  Have you seen any examples where you'd need both?
