### ISSUE TITLE
Error installing tensorflow

### ISSUE THREAD

**Issue by nickjalbert** [agentos-project/agentos#31]
When I run the following on a clean environment:

```
$ pip install -r dev-requirements.txt
```

I get the following error:

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0 (from -r dev-requirements.txt (line 19)) (from versions: none)
ERROR: No matching distribution found for tensorflow==2.2.0 (from -r dev-requirements.txt (line 19))
```

I'm guessing this is related to the vulnerability that [Dependabot](https://github.com/agentos-project/agentos/security/dependabot/dev-requirements.txt/tensorflow/open) is complaining about here. 

Shall we upgrade tensorflow?

**Comment by andyk** [comment]
Which version of python are you running in your env?

**Comment by nickjalbert** [comment]
actually this might be a problem with my python, I'm on 3.9.

**Comment by andyk** [comment]
TF currently requires "Requires Python 3.5–3.8, pip and venv >= 19.0" (https://www.tensorflow.org/install/pip).

If we want to keep TF as a dependency, then we should make AgentOS also require Python 3.5-3.8. Currently the docs only specify that AgentOS requires >=3.5.

**Comment by nickjalbert** [comment]
Downgrading to 3.8 and seeing what happens

**Comment by nickjalbert** [comment]
alright looks like 3.8 was the solution.  I'll update the docs to say Python 3.5-3.8

**Comment by andyk** [comment]
I've been thinking about changing the example_agents to use PyTorch instead of TF. It looks like PyTorch supports >=3.5 https://pytorch.org/get-started/locally/. Also, I believe PyTorch is more popular with researchers who are likely to make up a major portion of AgentOS early adopters.
