### ISSUE TITLE
Recently added test `test_registry_from_repo` takes too long to run

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#327]
recently added test `test_registry_from_repo` takes minutes to complete because it is testing `Registry.from_repo_inferred()` which does a recursive file name search (via `Path.rglob`) on the entire agentos github repo directory. I'm guessing this `rglob` takes so long because it is searching through some unecessary dirs such as `.git`.

This is slowing down our tests.

`Registry.from_repo_inferred()` can probably ignore dot files which might speed it up by a lot.

**Comment by nickjalbert** [comment]
We just discovered that if you comment out the `fetch()` in `repo.py` for existing repos, the test runs almost instantaneously.  See also #341

**Comment by andyk** [comment]
I deleted that line in #342
