### ISSUE TITLE
Add --release flag to build_docs.py

### ISSUE THREAD

**Issue by nickjalbert** [agentos-project/agentos#34]
Feature that would streamline the web release process a bit:

> Add a --release flag to build_docs.py that causes the output to go to docs/<curr_version> and the latest symlink to be updated. And then, when the flag isn't passed have the standard output location be documentation/_build which is already ignored by git, and which I think is, by convention, the standard location of sphinx output

See additional context in #32.

**Comment by andyk** [comment]
This as completed partly by d436348912586e5d0ca30c6f4961419891f90d85 (Which set build output to be a versioned sub folder) and partly thereafter (the soft linking latest)
