### ISSUE TITLE
Update text on index.html redirect page so that crawlers show a better preview

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#49]
I noticed today when I sent a link to agentos.org via Line messenger, it sent a summary blurb that was generated using html of the `index.html` page (which exists only in the ``website`` branch). Here is what it captured:

>**Page Redirection**
>If you are not redirected
>automatically, click to visit the mos...

We currently use a meta tag in the head to redirect:
https://github.com/agentos-project/agentos/blob/470c2d1dc9bc7ebd7703c157e0eeef0cfa5529e9/docs/index.html#L5

The text that is getting used is coming from line 9

https://github.com/agentos-project/agentos/blob/470c2d1dc9bc7ebd7703c157e0eeef0cfa5529e9/docs/index.html#L9

...and line 12

https://github.com/agentos-project/agentos/blob/470c2d1dc9bc7ebd7703c157e0eeef0cfa5529e9/docs/index.html#L12

This text could be updated to say 

>AgentOS: a learning agent platform

and

>Open Source python API & CLI for developing learning agents. This page should redirect to the latest AgentOS documentation. If you are not redirected automatically, click to visit the <a href='https://agentos.org/latest/'>most recent agentos docs</a>.

**Comment by ShrillShrestha** [comment]
Hey @andyk,
Do you want:

> https://github.com/agentos-project/agentos/blob/470c2d1dc9bc7ebd7703c157e0eeef0cfa5529e9/docs/index.html#L9

to be updated to:
`<title> AgentOS: a learning agent platform </title>`
and

> https://github.com/agentos-project/agentos/blob/470c2d1dc9bc7ebd7703c157e0eeef0cfa5529e9/docs/index.html#L12

to be updated to:
`Open Source python API & CLI for developing learning agents. This page should redirect to the latest AgentOS documentation. If you are not redirected automatically, click to visit<a href='https://agentos.org/latest/'>most recent agentos docs</a>.` ?

P.S. I am just a beginner. Please forgive my novice question.

**Comment by andyk** [comment]
Yep, that's right!

**Comment by ShrillShrestha** [comment]
@andyk, thanks I will make the change and create a PR. :)
