### ISSUE TITLE
MVP Component System (ACS) for Envs, Policies, and Agents

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#68]
Like `pip` but for Envs, Policies, and Agents.

It should:
* reuse the existing OpenAI env registery
* make it easy to see which envs, agents, policies are compatible with each other (per action and obs spaces)
* provide free hosting, 
* make it easy to search, install, upgrade 
* Integrate with **Agent Directories**

**Comment by nickjalbert** [comment]
PR open for initial design doc: https://github.com/agentos-project/design_docs/pull/1
